#!/usr/bin/env node
const { log } = require("console");
const Eta = require("eta");
const fs = require("fs");

version = "v1.0.0";

const template = fs.readFileSync("./templates/index.html", "utf8");
const docs = JSON.parse(fs.readFileSync(`./docs/${version}/docs.json`, "utf8"));

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

const groups = Object.entries(docs).reduce((groups, [name, module]) => {
  const tslug = slugify(module.type);
  const nslug = slugify(name);
  groups[tslug] ||= [];
  groups[tslug].push({ name, typeslug: tslug, slug: nslug, ...module });
  return groups;
}, {});

const modules = [
  "instruments",
  "synths",
  "modulators",
  "pulse",
  "note effects",
  "audio effects",
  "effect chain",
  "other",
].map((name) => {
  const slug = slugify(name);
  return {
    name,
    slug,
  };
});

const compiled = Eta.render(template, {
  docs: groups,
  modules,
});
fs.writeFileSync(`./docs/${version}/index.html`, compiled);
